stage = "Season"
registration_path = "raw/00_登记"

[reward_policy.complete]
ww = 30
tsb = 50
energy = 1
credit = 10
[reward_policy.missing1]
ww = 20
tsb = 40
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
[[round.group.thread]]
name = "A组"
path = "raw/01_初赛_a"
duplicate = []
choices = [
    [
        "神乐@3年Z班银八老师",
    ],
    [
        "社美胡@想吃掉我的非人少女",
    ],
    [
        "青海阳@千岁同学在波子汽水瓶内",
    ],
    [
        "阿莫尔@永远的黄昏",
    ],
    [
        "月之森真白@朋友的妹妹只缠着我",
    ],
    [
        "贝姬·布莱克贝尔@间谍过家家 Season 3",
    ],
    [
        "天道靡@乱马1/2 第2期",
    ],
    [
        "丽日御茶子@我的英雄学院 FINAL SEASON",
    ],
    [
        "耳郎响香@我的英雄学院 FINAL SEASON",
    ],
    [
        "水叶@致不灭的你 Season3",
    ],
    [
        "春日@妖怪旅馆营业中 贰",
    ],
    [
        "古拉娜特·尼达吉塔@婚戒物语 第2期",
    ],
    [
        "阿格妮@拥有超常技能的异世界流浪美食家2",
    ],
    [
        "莉兹·斯玛特@叹气的亡灵想隐退 第2期",
    ],
    [
        "冬村四织@SANDA",
    ],
    [
        "宫尾恩@绝妙舞步",
    ],
    [
        "木更@跨越种族与你相恋",
    ],
    [
        "双见奈奈@这里是充满笑容的职场。",
    ],
    [
        "角馆塔子@这里是充满笑容的职场。",
    ],
    [
        "铁轮梓@不中用的前辈。",
    ],
    [
        "小田岛@不动声色的柏田与喜形于色的太田",
    ],
    [
        "岩田朔英@星辰光辉更胜太阳",
    ],
    [
        "玛丽@机械女仆·玛丽",
    ],
    [
        "病田色@忍者和极道",
    ],
    [
        "玉井咲@胖子与爱情以及过错！",
    ],
    [
        "蒂娜@野生的最终BOSS出现了！",
    ],
    [
        "贝涅特纳修@野生的最终BOSS出现了！",
    ],
    [
        "悠尔哈·艾森兹@队友太弱所以贯彻辅助的宫廷魔法师，惨遭流放目标却是最强",
    ],
    [
        "青雪@差点在迷宫深处被信任的伙伴杀掉，但靠着天赐技能「无限扭蛋」获得等级9999的伙伴，我要向前队友和世界展开复仇&「给他们好看！」",
    ],
    [
        "奥莉珍@转生后的我成了英雄爸爸和精灵妈妈的女儿",
    ],
    [
        "莉莉娅@无职英雄 技能什么的毫无用处",
    ],
    [
        "塞思@古诺希亚",
    ],
    [
        "凛音@怪物弹珠 Deadverse Reloaded",
    ],
    [
        "柳生九兵卫@3年Z班银八老师",
    ],
    [
        "莫里翁·爱莉·诺卡那堤卡@婚戒物语 第2期",
    ],
    [
        "迪安娜@最后再拜托您一件事可以吗",
    ],
    [
        "菲迪丝@永远的黄昏",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/01_初赛_b"
duplicate = []
choices = [
    [
        "志村妙@3年Z班银八老师",
    ],
    [
        "柊夕湖@千岁同学在波子汽水瓶内",
    ],
    [
        "西野明日风@千岁同学在波子汽水瓶内",
    ],
    [
        "宵暗@永远的黄昏",
    ],
    [
        "影石堇@朋友的妹妹只缠着我",
    ],
    [
        "菲奥娜·弗洛斯特@间谍过家家 Season 3",
    ],
    [
        "天道霞@乱马1/2 第2期",
    ],
    [
        "芦户三奈@我的英雄学院 FINAL SEASON",
    ],
    [
        "玛琦@致不灭的你 Season3",
    ],
    [
        "秋音律子@蓝色管弦乐 第2期",
    ],
    [
        "阿凉@妖怪旅馆营业中 贰",
    ],
    [
        "萨菲尔·玛莎@婚戒物语 第2期",
    ],
    [
        "吉莎尔@拥有超常技能的异世界流浪美食家2",
    ],
    [
        "西朵莉·斯玛特@叹气的亡灵想隐退 第2期",
    ],
    [
        "小野一会@SANDA",
    ],
    [
        "洋子@终末摩托游",
    ],
    [
        "石川月菜@不擅吸血的吸血鬼",
    ],
    [
        "佐藤枫@这里是充满笑容的职场。",
    ],
    [
        "浅仓栞@这里是充满笑容的职场。",
    ],
    [
        "堀田美绪@不中用的前辈。",
    ],
    [
        "吉田清子@矢野同学的普通日常",
    ],
    [
        "小野寺翡翠@星辰光辉更胜太阳",
    ],
    [
        "伊雅娜·玛格诺莉亚@转生恶女的黑历史",
    ],
    [
        "雄鹰斗女@忍者和极道",
    ],
    [
        "艾蜜莉亚·罗丝寇兹@身为暗杀者的我明显比勇者还强",
    ],
    [
        "莉布拉@野生的最终BOSS出现了！",
    ],
    [
        "斯卡蕾特·艾尔·班迪米昂@最后再拜托您一件事可以吗",
    ],
    [
        "库拉斯阿·安妮罗洁@队友太弱所以贯彻辅助的宫廷魔法师，惨遭流放目标却是最强",
    ],
    [
        "艾莉@差点在迷宫深处被信任的伙伴杀掉，但靠着天赐技能「无限扭蛋」获得等级9999的伙伴，我要向前队友和世界展开复仇&「给他们好看！」",
    ],
    [
        "布洛莱特@素材采集家的异世界旅行记",
    ],
    [
        "高木京子@希维司：英雄之声",
    ],
    [
        "SQ@古诺希亚",
    ],
    [
        "八云@怪物弹珠 Deadverse Reloaded",
    ],
    [
        "凯萨琳@3年Z班银八老师",
    ],
    [
        "地狱的吹雪@一拳超人 第3期",
    ],
    [
        "梅琳达·德斯蒙@间谍过家家 Season 3",
    ],
    [
        "绫濑荠@千岁同学在波子汽水瓶内",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "C组"
path = "raw/01_初赛_c"
duplicate = []
choices = [
    [
        "八百岁比名子@想吃掉我的非人少女",
    ],
    [
        "内田优空@千岁同学在波子汽水瓶内",
    ],
    [
        "黄昏@永远的黄昏",
    ],
    [
        "薄暮@永远的黄昏",
    ],
    [
        "阿尼亚·福杰@间谍过家家 Season 3",
    ],
    [
        "乱马@乱马1/2 第2期",
    ],
    [
        "珊璞@乱马1/2 第2期",
    ],
    [
        "蛙吹梅雨@我的英雄学院 FINAL SEASON",
    ],
    [
        "托娜莉@致不灭的你 Season3",
    ],
    [
        "小樱春@蓝色管弦乐 第2期",
    ],
    [
        "野中姬乃@婚戒物语 第2期",
    ],
    [
        "安巴鲁·伊达卡农@婚戒物语 第2期",
    ],
    [
        "露萨露卡@拥有超常技能的异世界流浪美食家2",
    ],
    [
        "露希亚·罗杰@叹气的亡灵想隐退 第2期",
    ],
    [
        "风尾二胡@SANDA",
    ],
    [
        "爱理@终末摩托游",
    ],
    [
        "佐久间瑛子@不擅吸血的吸血鬼",
    ],
    [
        "间瑞希@这里是充满笑容的职场。",
    ],
    [
        "猫手@这里是充满笑容的职场。",
    ],
    [
        "柏田@不动声色的柏田与喜形于色的太田",
    ],
    [
        "芽衣@矢野同学的普通日常",
    ],
    [
        "香川美织@星辰光辉更胜太阳",
    ],
    [
        "可诺哈·玛格诺莉亚@转生恶女的黑历史",
    ],
    [
        "山姆·杨@Let's Play 充满挑战的人生",
    ],
    [
        "莉亚·拉古恩@身为暗杀者的我明显比勇者还强",
    ],
    [
        "帕德嫩@野生的最终BOSS出现了！",
    ],
    [
        "缇蕾娜扎·霍普金斯@最后再拜托您一件事可以吗",
    ],
    [
        "梅依@差点在迷宫深处被信任的伙伴杀掉，但靠着天赐技能「无限扭蛋」获得等级9999的伙伴，我要向前队友和世界展开复仇&「给他们好看！」",
    ],
    [
        "涅姆姆@差点在迷宫深处被信任的伙伴杀掉，但靠着天赐技能「无限扭蛋」获得等级9999的伙伴，我要向前队友和世界展开复仇&「给他们好看！」",
    ],
    [
        "噗尼@素材采集家的异世界旅行记",
    ],
    [
        "成宫魅羽@希维司：英雄之声",
    ],
    [
        "拉琪奥@古诺希亚",
    ],
    [
        "尼欧@怪物弹珠 Deadverse Reloaded",
    ],
    [
        "小玉@3年Z班银八老师",
    ],
    [
        "爱娃·廉菲德@叹气的亡灵想隐退 第2期",
    ],
    [
        "音井@朋友的妹妹只缠着我",
    ],
    [
        "紫阳花@永远的黄昏",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "D组"
path = "raw/01_初赛_d"
duplicate = []
choices = [
    [
        "近江汐莉@想吃掉我的非人少女",
    ],
    [
        "七濑悠月@千岁同学在波子汽水瓶内",
    ],
    [
        "王真树永远@永远的黄昏",
    ],
    [
        "小日向彩羽@朋友的妹妹只缠着我",
    ],
    [
        "西尔维亚·舍伍德@间谍过家家 Season 3",
    ],
    [
        "天道茜@乱马1/2 第2期",
    ],
    [
        "战栗的龙卷@一拳超人 第3期",
    ],
    [
        "八百万百@我的英雄学院 FINAL SEASON",
    ],
    [
        "喵咪@致不灭的你 Season3",
    ],
    [
        "津场木葵@妖怪旅馆营业中 贰",
    ],
    [
        "奈富莉缇丝·罗姆卡@婚戒物语 第2期",
    ],
    [
        "柠丽露@拥有超常技能的异世界流浪美食家2",
    ],
    [
        "蒂诺‧薛德@叹气的亡灵想隐退 第2期",
    ],
    [
        "库琉丝·亚尔根@叹气的亡灵想隐退 第2期",
    ],
    [
        "湾田光莉@绝妙舞步",
    ],
    [
        "朝霞万理@跨越种族与你相恋",
    ],
    [
        "楠木美纱@不擅吸血的吸血鬼",
    ],
    [
        "梨田亚里沙@这里是充满笑容的职场。",
    ],
    [
        "泷泽莲@这里是充满笑容的职场。",
    ],
    [
        "田渊@不动声色的柏田与喜形于色的太田",
    ],
    [
        "泉@矢野同学的普通日常",
    ],
    [
        "神城昴@星辰光辉更胜太阳",
    ],
    [
        "胶带@忍者和极道",
    ],
    [
        "幸田梦子@胖子与爱情以及过错！",
    ],
    [
        "露法斯·玛法尔@野生的最终BOSS出现了！",
    ],
    [
        "薇尔戈@野生的最终BOSS出现了！",
    ],
    [
        "梅尔菲拉·马歇尔瑞德@恶食千金与狂血公爵",
    ],
    [
        "娜芝娜@差点在迷宫深处被信任的伙伴杀掉，但靠着天赐技能「无限扭蛋」获得等级9999的伙伴，我要向前队友和世界展开复仇&「给他们好看！」",
    ],
    [
        "艾伦@转生后的我成了英雄爸爸和精灵妈妈的女儿",
    ],
    [
        "莱娜@无职英雄 技能什么的毫无用处",
    ],
    [
        "凪@希维司：英雄之声",
    ],
    [
        "吉娜@古诺希亚",
    ],
    [
        "猿飞菖蒲@3年Z班银八老师",
    ],
    [
        "来岛又子@3年Z班银八老师",
    ],
    [
        "可萝伊·韦尔达@叹气的亡灵想隐退 第2期",
    ],
    [
        "橘浅黄@朋友的妹妹只缠着我",
    ],
    [
        "埴安@永远的黄昏",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "初赛结果"
path = "raw/01_初赛结果"
duplicate = []
thread_type = "PollResult"

[[round]]
name = "第二轮"

[[round.group]]
[[round.group.thread]]
name = "决赛"
path = "raw/02_决赛"
duplicate = []
choices = [
    [
        "神乐@3年Z班银八老师",
    ],
    [
        "柊夕湖@千岁同学在波子汽水瓶内",
    ],
    [
        "阿尼亚·福杰@间谍过家家 Season 3",
    ],
    [
        "七濑悠月@千岁同学在波子汽水瓶内",
    ],
    [
        "青海阳@千岁同学在波子汽水瓶内",
    ],
    [
        "西野明日风@千岁同学在波子汽水瓶内",
    ],
    [
        "乱马@乱马1/2 第2期",
    ],
    [
        "小日向彩羽@朋友的妹妹只缠着我",
    ],
]
max_choice = 2
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "复活赛"
path = "raw/02_复活赛"
duplicate = []
choices = [
    [
        "贝姬·布莱克贝尔@间谍过家家 Season 3",
    ],
    [
        "社美胡@想吃掉我的非人少女",
    ],
    [
        "月之森真白@朋友的妹妹只缠着我",
    ],
    [
        "玛丽@机械女仆·玛丽",
    ],
    [
        "铁轮梓@不中用的前辈。",
    ],
    [
        "天道霞@乱马1/2 第2期",
    ],
    [
        "菲奥娜·弗洛斯特@间谍过家家 Season 3",
    ],
    [
        "影石堇@朋友的妹妹只缠着我",
    ],
    [
        "内田优空@千岁同学在波子汽水瓶内",
    ],
    [
        "珊璞@乱马1/2 第2期",
    ],
    [
        "八百岁比名子@想吃掉我的非人少女",
    ],
    [
        "战栗的龙卷@一拳超人 第3期",
    ],
    [
        "天道茜@乱马1/2 第2期",
    ],
    [
        "近江汐莉@想吃掉我的非人少女",
    ],
    [
        "蒂诺‧薛德@叹气的亡灵想隐退 第2期",
    ],
]
max_choice = 4
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "决赛结果"
path = "raw/02_决赛结果"
thread_type = "PollResult"
duplicate = []
